### PR TITLE
Removed babel and using typescript on tests

### PR DESCRIPTION
**Pull request by oizie**
- [x] Removed js files
- [x] Migrated and added types to the tests now in TS
- [x] Changed the build to only use tsc

### CODE REVIEW

**Comment by rcelha** [comment]
good job. But I think you over-deleted files in this PR 🤔

**Comment by rcelha** [comment]
Also, I'm not using npm but yarn. So please remove `package-lock.json`

**Comment by oizie** [comment]
Which files shouldn't I delete?

**Comment by oizie** [comment]
Yeah for some reason I was using npm and created that.

**Comment by rcelha** [comment]
> Which files shouldn't I delete?


- src/reducers/fetch-reducer.spec.js
- src/reducers/list-reducer.spec.js

**Comment by oizie** [comment]
Oh I see I removed some of the tests. My bad that actually was me cleaning stuff and end up deleting the entire folder and rolled back. Will push that in a sec

**Comment by oizie** [comment]
Here you go again my bad. That's what you get when you are trying to rush things.

**Pull request merged**
